server:
  port: 19095

spring:
  application:
    name: hub-service
  datasource:
    url: ${DB_URL}?currentSchema=hub_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  jpa:
    show-sql: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: hub_service
        format_sql: false
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:19090/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  tracing:
      sampling:
        probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

kakao:
  enabled: ${KAKAO_ENABLED:false}
  rest-api-key: ${KAKAO_REST_API_KEY:dummy-kakao-key-for-test}
  base-url: "https://dapi.kakao.com"

springdoc:
  servers:
    - url: ${SWAGGER_GATEWAY_URL:http://localhost:19091}
      description: API Gateway URL

swagger:
  gateway-url: ${SWAGGER_GATEWAY_URL:http://localhost:19091}

resilience4j:
  ratelimiter:
    instances:
      kakaoApi:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 5s
  retry: 
    instances:
      kakaoApi:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.HttpClientErrorException.TooManyRequests
          - org.springframework.web.client.ResourceAccessException
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 20s
    instances:
      company-service:
        baseConfig: default

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
