server:
  port: 19093

spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL}?currentSchema=user_service
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true

  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      default_schema: user_service
    show-sql: false
    defer-datasource-initialization: false
    open-in-view: false


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:19090/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 20s

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

message: default

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000
  refresh-expiration: 86400000

swagger:
  gateway-url: ${SWAGGER_GATEWAY_URL:http://localhost:19091}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
