name: delivery-service

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'delivery-service/**'
      - 'core-common/**'
      - 'Dockerfile'
      - 'build.gradle'
      - 'settings.gradle'
      - '.github/workflows/delivery-service.yml'
      - '.github/workflows/_reusable-ci-cd.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'delivery-service/**'
      - 'core-common/**'

jobs:
  ci-cd:
    uses: ./.github/workflows/_reusable-ci-cd.yml
    with:
      service_name: delivery-service
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
