name: eureka-server

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'eureka-server/**'

      - 'Dockerfile'
      - 'build.gradle'
      - 'settings.gradle'
      - '.github/workflows/eureka-server.yml'
      - '.github/workflows/_reusable-ci-cd.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'eureka-server/**'


jobs:
  ci-cd:
    uses: ./.github/workflows/_reusable-ci-cd.yml
    with:
      service_name: eureka-server
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
