server:
  port: 19090

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:19090/eureka/}
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: false
        service-id: config-server

management:
  endpoints:
    web:
      exposure:
        include: health, refresh

logging:
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
