server:
  port: 19092

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPO_PATH:file:./config-repo/}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:19090/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
